name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv tool install ruff
      - name: Ruff linter
        run: uv run ruff check
      - name: Ruff formatter
        run: uv run ruff format --check
      # - name: Run tests
        # run: uv run pytest tests